In [ ]:
pip install tensorflow==2.8.0


     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 497.6/497.6 MB 1.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.6/42.6 kB 3.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.8/5.8 MB 45.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 462.5/462.5 kB 29.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 56.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.9/4.9 MB 50.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 781.3/781.3 kB 51.5 MB/s eta 0:00:00
  Attempting uninstall: keras
    Found existing installation: keras 2.15.0
    Uninstalling keras-2.15.0:
      Successfully uninstalled keras-2.15.0
  Attempting uninstall: tensorboard-data-server
    Found existing installation: tensorboard-data-server 0.7.2
    Uninstalling tensorboard-data-server-0.7.2:
      Successfully uninstalled tensorboard-data-server-0.7.2
  Attempting uninstall: google-auth-oauthlib
    Found existing 

In [ ]:
# Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [ ]:
# Load the CSV files from Google Drive
train_path = '/content/drive/MyDrive/data-set/fashion-mnist-train/fashion-mnist-train.csv'
test_path = '/content/drive/MyDrive/data-set/fashion-mnist-test/fashion-mnist-test.csv'

In [ ]:
df_train = pd.read_csv(train_path)
df_test = pd.read_csv(test_path)

In [ ]:
# Extracting features (pixel values) and labels
X = df_train.iloc[:, 1:]
y = df_train.iloc[:, 0]

test_X = df_test.iloc[:, 1:]
test_y = df_test.iloc[:, 0]


In [ ]:
# Feature Scaling
X = X / 255
test_X = test_X / 255


In [ ]:
# Split data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

In [ ]:
# Bayesian Regression (Naive Bayes) Model
nb_classifier = GaussianNB()

In [ ]:
# Train the model
nb_classifier.fit(X_train, y_train)


GaussianNB()

In [ ]:
# Predictions on the test set
nb_predictions = nb_classifier.predict(test_X)


In [ ]:
# Evaluate the model
nb_accuracy = accuracy_score(test_y, nb_predictions)

# Display accuracy
print(f'Accuracy using Bayesian Regression: {nb_accuracy * 100:.3f}%')

Accuracy using Bayesian Regression: 58.790%


In [ ]:
# Display confusion matrix and classification report
print("\nConfusion Matrix:")
print(confusion_matrix(test_y, nb_predictions))


Confusion Matrix:
[[605  51  26 181  81   0  16   0  40   0]
 [  0 943  15  30   2   1   9   0   0   0]
 [  2  11 386  65 501   0  14   0  21   0]
 [  6 390   8 564  25   0   4   0   3   0]
 [  0  39  50 152 748   0   2   0   9   0]
 [  1   1   2   2   0 295   5 648  14  32]
 [117  41 130 226 413   0  27   0  46   0]
 [  0   0   0   0   0   5   0 978   0  17]
 [  1   3  37  78 152   3  17   3 705   1]
 [  0   0   0   1   0  31   3 326  11 628]]


In [ ]:
print("\nClassification Report:")
print(classification_report(test_y, nb_predictions))


Classification Report:
              precision    recall  f1-score   support

           0       0.83      0.60      0.70      1000
           1       0.64      0.94      0.76      1000
           2       0.59      0.39      0.47      1000
           3       0.43      0.56      0.49      1000
           4       0.39      0.75      0.51      1000
           5       0.88      0.29      0.44      1000
           6       0.28      0.03      0.05      1000
           7       0.50      0.98      0.66      1000
           8       0.83      0.70      0.76      1000
           9       0.93      0.63      0.75      1000

    accuracy                           0.59     10000
   macro avg       0.63      0.59      0.56     10000
weighted avg       0.63      0.59      0.56     10000

